### ISSUE TITLE
Ensure extension works on Firefox

### ISSUE THREAD

**Issue by aspiers** [rolod0x/rolod0x#19]
## Current status of support

- [x] Get settings page working
- [x] Get address replacement working
- [x] Get settings opening in dedicated tab - **should be fixed by #273**
- [x] Get address search via hotkey working - **should be fixed by #273**
- [x] Get address search via popup menu working - **should be fixed by #273**
- [x] Get right-click to add address label working - **should be fixed by #273**
- [ ] Get built-in list of sites enabled by default - **this may be impossible**

Basically anything relating to the background script doesn't work.

## Help needed with testing

Do you want rolod0x to support Firefox? You can help make it happen! While a Firefox `.zip` hasn't been included in a release yet, they're already being built automatically by the CI, so you can download, test, and report back here or in https://github.com/rolod0x/rolod0x/discussions/274 what isn't working.  Just go to [this list of successful builds](https://github.com/aspiers/rolod0x/actions/workflows/build-zip.yml?query=is%3Asuccess+branch%3Amain), click on the top one, scroll to the bottom of the build page, and click on the firefox artifact:

![image](https://github.com/aspiers/rolod0x/assets/100738/14d220a9-df55-447a-843b-17a63ddfeaac)

Then follow the installation guide for Chrome as it works in more or less the same way.

As soon as you encounter a problem (which may be very early at the time of writing), just come back to this issue and post details.  Screenshots are helpful!

## Useful resources

- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background#browser_support
- https://blog.mozilla.org/addons/2024/03/13/manifest-v3-manifest-v2-march-2024-update/
- https://extensionworkshop.com/documentation/develop/getting-started-with-web-ext/#testing-out-an-extension

## Old info, no longer relevant

See [fregante/browser-extension-template#78](https://github.com/fregante/browser-extension-template/issues/%378).

Possible approach to solution: https://github.com/transclude-me/extension/commit/78b529ef1af32ba076b3b852f21145f48dfdb1b9#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by 0xAurelius** [comment]
Did some initial Firefox testing on Windows with v1.3.0 and noticed a few issues:
- Firefox defaults to extensions only being able to read and write data when the extension is clicked: 
![image](https://github.com/rolod0x/rolod0x/assets/91024694/c2c06ea7-c5a0-4cee-9393-c34a6b1cc351)
- Right click to save address doesn't seem to work, had to add it manually via the extension settings

**Comment by aspiers** [comment]
Thanks a lot! This matches my experience during (very limited) testing, and also my expectations. I think I know most of what's going on and hopefully won't be too hard to fix a lot of this.

**Comment by aspiers** [comment]
I get the impression from https://bugzilla.mozilla.org/show_bug.cgi?id=1766026 that Firefox intends to drop support for `host_permissions`, or already has done, in favour of `optional_host_permissions`.  The former is the way rolod0x implements a list of built-in sites which are enabled by default.  I guess we can start by having all sites disabled by default, and then if there's a way to automatically enable the most commonly used ones then we can add that later.

Right-click I'm pretty sure doesn't work due to the Firefox MV3 manifest not configuring the background worker in the right way.

**Comment by aspiers** [comment]
Have figured out a bunch of stuff and updated description above.
